### ISSUE TITLE
could there be a release, please!?

### ISSUE THREAD

**Issue by hannesm** [mirage/encore#21]
it looks like https://api.travis-ci.org/v3/job/606167835/log.txt fails (compiling ocaml-git test suite) with 
```
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Bigarray referenced from /home/travis/.opam/ocaml-base-compiler.4.07.1/lib/encore/Encore.cmxa(Encore__Lole)
```

which seems to be fixed in master since #19 -- but that has not been released yet. thanks!

**Comment by dinosaure** [comment]
Done by https://github.com/ocaml/opam-repository/pull/15257.
